---
- hosts: beta:&webservers
  user: sre
  become: yes
  vars:
    message: "I am an beta web server"
  tasks:
  - name: Update the motd file
    copy: content="{{ message }}" dest=/etc/motd owner=root group=root mode=0644

- hosts: beta:&workers
  user: sre
  become: yes
  vars:
    message: "I am an beta worker"
  tasks:
  - name: Update the motd file
    copy: content="{{ message }}" dest=/etc/motd owner=root group=root mode=0644
