---
- hosts: charlie:&webservers
  user: sre
  become: yes
  vars:
    message: "I am an charlie web server"
  tasks:
  - name: Update the motd file
    copy: content="{{ message }}" dest=/etc/motd owner=root group=root mode=0644

- hosts: charlie:&workers
  user: sre
  become: yes
  vars:
    message: "I am an charlie worker"
  tasks:
  - name: Update the motd file
    copy: content="{{ message }}" dest=/etc/motd owner=root group=root mode=0644
