---
- hosts: delta:&webservers
  user: sre
  become: yes
  vars:
    message: "I am an delta web server"
  tasks:
  - name: Update the motd file
    copy: content="{{ message }}" dest=/etc/motd owner=root group=root mode=0644

- hosts: delta:&workers
  user: sre
  become: yes
  vars:
    message: "I am an delta worker"
  tasks:
  - name: Update the motd file
    copy: content="{{ message }}" dest=/etc/motd owner=root group=root mode=0644
